apiVersion : apps/v1
kind: Deployment
metadata:
  name: helloroseworld001 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloroseworld001
  template:
    metadata:
      labels:
        app: helloroseworld001 
    spec:
      containers:
        - name: helloroseworld001 
          image: zzacr.azurecr.io/helloroseworld001
          ports:
          - containerPort: 2999