trigger:
- none

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: deploy_dev
    displayName: 'Deploy in dev env'
    variables: 
    - group: aks-deploy-dev
    jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: $(vmImageName)
      environment: 'iveetechgeekready2021-dev.geekready2021'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: deploy-aks-app.steps.yml
              parameters:
                dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
                imagePullSecret: '$(imagePullSecret)'
                containerRegistry: '$(containerRegistry)'
                imageRepository: '$(imageRepository)'
                imageTag: ${{ parameters.imageTag }}
  - stage: deploy_test
    displayName: 'Deploy in test env'
    dependsOn: deploy_dev
    variables: 
    - group: aks-deploy-test
    jobs:
    - deployment: Deploy
      displayName: Deploy
      pool:
        vmImage: $(vmImageName)
      environment: 'iveetechgeekready2021-test.geekready2021'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: deploy-aks-app.steps.yml
              parameters:
                dockerRegistryServiceConnection: '$(dockerRegistryServiceConnection)'
                imagePullSecret: '$(imagePullSecret)'
                containerRegistry: '$(containerRegistry)'
                imageRepository: '$(imageRepository)'
                imageTag: '$(imageTag)'
  
# - stage: deploy-dev
#   displayName: Deploy in Dev env
#   jobs:
#   - deployment: Deploy
#     displayName: Deploy
#     pool:
#       vmImage: $(vmImageName)
#     environment: 'iveetechgeekready2021-dev.geekready2021'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - checkout: self
#           - task: KubernetesManifest@0
#             displayName: Create imagePullSecret
#             inputs:
#               action: createSecret
#               secretName: $(imagePullSecret)
#               dockerRegistryEndpoint: $(dockerRegistryServiceConnection)

#           - task: KubernetesManifest@0
#             displayName: Deploy to Kubernetes cluster
#             inputs:
#               action: deploy
#               manifests: |
#                 $(Build.SourcesDirectory)/src/rose/k8s/pipeline/rose-app-dep.yml
#                 $(Build.SourcesDirectory)/src/rose/k8s/pipeline/rose-app-svc.yml
#                 $(Build.SourcesDirectory)/src/rose/k8s/pipeline/rose-app-hpa-cpu.yml
#               imagePullSecrets: |
#                 $(imagePullSecret)
#               containers: |
#                 $(containerRegistry)/$(imageRepository):$(tag)
