apiVersion: v1
kind: Service
metadata:
  name: {{ template "rose-app.fullname" .}}-svc
  labels:
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 2999
  selector:
    app: {{ .Values.roseApp.name }}